name: Update Data

on:
  push:
    branches:
      - main

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install axios

    - name: Run JavaScript script
      run: node path_to_your_js_script.js
