name: Update JSON with Gold Value

on:
  push:
    paths:
      - 'gold_value.txt'

jobs:
  update-gold-value:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read gold value from txt and update JSON
        run: |
          gold_value=$(cat gold_value.txt)
          jq --arg gold_value "$gold_value" '.gold = $gold_value' game_data.json > data.json

      - name: Commit and push if changes
        run: |
          git config --local user.email "{{secrets.MY_EMAIL}}"
          git config --local user.name "{{secrets.MY_NAME}}"
          git add data.json
          git diff --staged --quiet || (git commit -m "Update gold value in JSON" && git push)
