name: Get Gold Value

on:
  push:
    branches:
      - main

jobs:
  get_gold_value:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run script to get gold value
      run: |
        git config --local user.enail "{{secrets.MY_EMAIL}}"
        git config --local user.enail "{{secrets.MY_NAME}}"
        python get_gold_value.py
