name: Update Gold Value

on:
  workflow_dispatch

jobs:
  update-gold-value:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch JSON data
      run: |
        JSON_DATA=$(curl -s '${{ secrets.GOLD_URL_SECRET }}')   # 替换 YOUR_JSON_URL 为实际的 JSON URL
        echo "$JSON_DATA" > data.json

    - name: Extract gold value for rank 1
      run: |
        GOLD_VALUE=$(jq -r '.data.rank[] | select(.rank == 1) | .gold' data.json)
        echo "Gold value for rank 1: $GOLD_VALUE"

    - name: Remove existing gold.txt
      run: |
        rm -f gold.txt

    - name: Save updated gold value to file
      run: |
        echo "${GOLD_VALUE}" > gold.txt

    - name: Commit and push changes
      run: |
        git config --local user.email "${{ secrets.MY_EMAIL }}"
        git config --local user.name "${{ secrets.MY_NAME }}"
        git add gold.txt
        git commit -m "Update gold value from JSON"
        git push -u origin master
        git pull
        git push
